# 工作流名称
name: 编译报告并发布到 Release (Compile and Release PDFs)

# 触发条件：推送到 master 分支时
on:
  push:
    branches:
      - master

# 工作流任务
jobs:
  build_and_release:
    # 运行环境
    runs-on: ubuntu-latest
    
    # 授予工作流写入仓库内容的权限
    permissions:
      contents: write

    steps:
      # 第 1 步：检出仓库代码
      - name: 检出仓库代码 (Checkout repository)
        uses: actions/checkout@v2 # 使用 v2 或更高版本

      # 第 2 步：使用优化后的 Action 编译 LaTeX
      - name: 编译 LaTeX 文档 (Compile LaTeX document)
        uses: HermitSun/latex-action@v3
        with:
          # 使用 glob 模式自动查找所有 .tex 文件，并排除 template 目录下的
          root_file: |
            *.tex
            */*.tex
            !template/*.tex
          glob_root_file: true
          
          # 直接指定使用 XeLaTeX 编译器
          latexmk_use_xelatex: true
          
          # 使用专门的输入来安装 Noto CJK 字体包
          extra_system_packages: "font-noto-cjk"
          
          # 在编译前执行脚本，用 sed 替换字体名称，这是最可靠的方法
          pre_compile: |
            echo "正在替换 LaTeX 源文件中的字体名称..."
            find . -type f -name "*.tex" -exec sed -i 's/SimSun/Noto Serif CJK SC/g' {} +
            find . -type f -name "*.tex" -exec sed -i 's/SimHei/Noto Sans CJK SC/g' {} +

      # 第 3 步：创建或更新 Release 并上传 PDF
      - name: 创建/更新 Release 并上传PDF (Create/Update Release and Upload PDFs)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest-reports
          name: 最新实验报告 (Latest Reports)
          body: |
            自动编译生成的最新实验报告PDF。
            此 Release 由 GitHub Action 自动更新。
          prerelease: true
          # 使用通配符上传所有生成的 PDF 文件
          files: |
            *.pdf
            */*.pdf
