# 工作流名称
name: 编译报告并发布到 Release (Compile and Release PDFs)

# 触发条件：推送到 master 分支时
on:
  push:
    branches:
      - master

# 工作流任务
jobs:
  build_and_release:
    # 运行环境
    runs-on: ubuntu-latest
    
    # 授予工作流写入仓库内容的权限
    permissions:
      contents: write

    steps:
      # 第 1 步：检出仓库代码
      - name: 检出仓库代码 (Checkout repository)
        uses: actions/checkout@v4

      # 第 2 步：安装字体、安装 TeX Live 环境并使用 xelatex 编译
      - name: 安装字体并编译 (Install Fonts & Compile)
        uses: xu-cheng/texlive-action@v2
        with:
          scheme: full
          # 使用 run 参数，让下面的脚本在已安装 TeX Live 的环境中执行
          run: |
            # 关键步骤：更新包列表并安装中文字体
            echo "正在安装中文字体..."
            apt-get update
            apt-get install -y fonts-wqy-zenhei fonts-noto-cjk
            
            # 关键步骤：刷新系统字体缓存，让 XeTeX 能找到新字体
            echo "正在刷新字体缓存..."
            fc-cache -f -v

            echo "字体准备就绪，开始在 TeX Live 环境中编译..."
            mkdir -p compiled_reports
            for file in $(find . -type f -name "*.tex" ! -path "./template/*" ! -name "template.tex"); do
              echo "正在编译: $file"
              # 使用 xelatex 编译器
              latexmk -xelatex -output-directory=compiled_reports -cd "$file"
            done
            echo "所有文件编译完成。"

      # 第 3 步：创建或更新 Release 并上传 PDF
      - name: 创建/更新 Release 并上传PDF (Create/Update Release and Upload PDFs)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest-reports
          name: 最新实验报告 (Latest Reports)
          body: |
            自动编译生成的最新实验报告PDF。
            此 Release 由 GitHub Action 自动更新。
          prerelease: true
          files: compiled_reports/*.pdf
