# 工作流名称
name: 测试文件上传到 Release (Test File Upload to Release)

# 触发条件：推送到 master 分支时
on:
  push:
    branches:
      - master

# 工作流任务
jobs:
  upload_test_file:
    # 运行环境
    runs-on: ubuntu-latest
    
    # 授予工作流写入仓库内容的权限
    permissions:
      contents: write

    steps:
      # 第 1 步：检出仓库代码 (这是必须的，否则无法访问仓库文件)
      - name: 检出仓库代码 (Checkout repository)
        uses: actions/checkout@v2

      # 第 2 步：创建一个新的 Release 并上传指定文件
      - name: 创建 Release 并上传测试文件 (Create Release and Upload Test File)
        uses: softprops/action-gh-release@v2
        with:
          # 使用 GitHub Actions 的内置运行编号作为标签，确保唯一性
          tag_name: test-upload-${{ github.run_number }}
          # Release 的标题
          name: 测试文件上传 #${{ github.run_number }}
          body: |
            此 Release 用于测试文件上传机制。
            上传的文件是: /大学物理实验-实验报告/Preport底板.tex
            Commit SHA: `${{ github.sha }}`
          # 标记为 "Latest"
          make_latest: true
          # 标记为预发布
          prerelease: true
          # 关键：指定要上传的文件路径
          files: 大学物理实验-实验报告/Preport底板.tex
